env:
  - PACKAGE_VERSION=0.1


language: c++

compiler:
  - gcc++
  - clang

install:
  make get-deps

before_script:

script:
  - make all

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - bin/example

