language: cpp
compiler:
	- clang
	- gcc
	
#before_install:

install: make get-deps

#before_script:
script: make

#after_success:
#after_failure:


#before_deploy:
#deploy:
#after_deploy:

#after_script: